### ISSUE TITLE
Can we get some basic documentation about how to use this please

### ISSUE THREAD

**Issue by Strider3000** [ssh-mitm/tcp-proxy-server#1]
subject - thanks

**Comment by manfred-kaiser** [comment]
This project is in a very early stage. Only the bindings to my other project "https://github.com/ssh-mitm/ssh-mitm" are defined.

At the moment, this project does not  work without my other project.

**Comment by manfred-kaiser** [comment]
https://github.com/ickerwx/tcpproxy is an interesting tcpproxy project

**Comment by manfred-kaiser** [comment]
The upcoming version 0.4.0 of ssh-mitm server (https://github.com/ssh-mitm/ssh-mitm) will include a tcpproxy.

If you can't wait for this release, you can checkout a development preview by switching to the "feature_tcpproxy" branch in the ssh-mitm project.


In the future, this repo will be used for a meta package, that will install "ssh-mitm".
